add golang ci lint
ArtemShalinFe/gophkeeper pull request #1
Opened 2023-10-17 12:45 UTC by ArtemShalinFe

2023-10-28 18:30 UTC, s-shpak requested changes
Артем, привет! Все в целом движется в правильном направлении, но мне не очень понятно, зачем в твоем подходе создавать агент, который крутится на твоей машине: я не нашел логики синхронизации с сервером. Нужен ли тебе агент

Кроме того, мне кажется, что логику получения данных стоит изменить. Я отправлю в чат группы мое видение, посмотри его, если будешь несогласен - давай обсудим

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/gagent
Бинарь попал в PR

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/main.go
> +	componentsErrs := make(chan error, 1)
Лучше определить длину буффера по количеству компонентов, которые могут писать в этот канал

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/main.go
> +			cancelCtx()
После отмены контекста можно продолжить логировать ошибки

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/main.go
> +			zap.L().Error("an unexpected error occurred in one of the application components", zap.Error(err))
Почему бы не использовать логгер, определенный ниже?

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/main.go
> +		syscall.SIGQUIT)
```suggestion
		syscall.SIGQUIT,
	)
```

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/main.go
> +	if err := gkclient.SetupConn(ctx); err != nil {
Нельзя ли поместить создание соединения в функцию инициализации клиента?

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/main.go
> +		return fmt.Errorf("an error occured while init conn to server client, err: %w", err)
```suggestion
		return fmt.Errorf("an error occured while init conn to server client: %w", err)
```

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/main.go
> +		if err := gagent.ListenAndServe(); err != nil {
`ListenAndServe` при `Shutdown` возвращает ошибку, ее лучше отфильтровать

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/main.go
> +		const timeoutServerShutdown = time.Second * 10
Лучше это вынести в константу куда-то наверх

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/main.go
> +		const timeoutShutdown = time.Second * 30
Это можно тоже вынести в блок констант-таймаутов

2023-10-28 18:30 UTC, s-shpak commented on cmd/gagent/main.go
> +		log.Fatal("failed to gracefully shutdown the service")
Не надо фаталиться здесь: выходить лучше всегда в одном месте. Эту информацию достаточно просто залогировать

2023-10-28 18:30 UTC, s-shpak commented on cmd/gclient/gclient
Бинарь

2023-10-28 18:30 UTC, s-shpak commented on cmd/gserver/gserver
Бинарь

2023-10-28 18:30 UTC, s-shpak commented on cmd/gserver/main.go
Все те же комментарии, что и к `main.go` агента

2023-10-28 18:30 UTC, s-shpak commented on internal/agent/agent.go
> +	log *zap.Logger) *Agent {
```suggestion
	log *zap.Logger,
) *Agent {
```

2023-10-28 18:30 UTC, s-shpak commented on internal/agent/agent.go
> +			// r.Use(h.JwtMiddleware)
deadcode

2023-10-28 18:30 UTC, s-shpak commented on internal/agent/agent.go
> +			var recordPathWithParam = path.Join(recordPath, "/{", recordIDParam, "}")
Переменная содержит такую строку: `/records/{/recordID/}`. Кажется, что это неправильно. Я просто использовал бы `fmt.Sprintf`

2023-10-28 18:30 UTC, s-shpak commented on internal/agent/handlers.go
> +func (h *Handlers) Record(ctx context.Context, w http.ResponseWriter, r *http.Request) {
```suggestion
func (h *Handlers) GetRecord(ctx context.Context, w http.ResponseWriter, r *http.Request) {
```

2023-10-28 18:30 UTC, s-shpak commented on internal/agent/handlers.go
> +func (h *Handlers) Records(ctx context.Context, w http.ResponseWriter, r *http.Request) {
```suggestion
func (h *Handlers) GetRecords(ctx context.Context, w http.ResponseWriter, r *http.Request) {
```

2023-10-28 18:30 UTC, s-shpak commented on internal/agent/handlers.go
> +	if update {
Тут довольно много логики, я бы разделил на два метода

2023-10-28 18:30 UTC, s-shpak commented on internal/agent/handlers.go
> +			w.WriteHeader(http.StatusConflict)
Не ясно, зачем работать с ResponseWriter на этом уровне: почему бы просто не передать ошибку наверх, там ее обработать и выставить соответсвующий статус?

2023-10-28 18:30 UTC, s-shpak commented on internal/agent/jwt.go
> +func userFromContext(ctx context.Context) (*models.User, bool) {
Кажется, что эта функция не должная лежать в `jwt.go`

2023-10-28 18:30 UTC, s-shpak commented on internal/models/data_types.go
> +	enc := gob.NewEncoder(&buff)
Gob не дает гарантий о прямой и обратной совместимостях. Лучше использовать другую сериализацию, например быстрый JSON или https://github.com/fxamacker/cbor

2023-10-28 18:30 UTC, s-shpak commented on internal/models/data_types.go
> +type Auth struct {
Надо ли для каждого объекта определять `ToByte` и `FromByte`. Кажется, что эти определения можно заменить одной функцией

2023-10-28 18:30 UTC, s-shpak commented on internal/models/data_types.go
> +		return nil, fmt.Errorf(errEncodeToByteTemplate, err)
Текст ошибки лучше генерировать в функции

2023-10-28 18:30 UTC, s-shpak commented on internal/models/metainfo.go
> +type Metainfo struct {
```suggestion
type Metadata struct {
```

2023-10-28 18:30 UTC, s-shpak commented on internal/models/records.go
> +var MaxFileSize = 20 * 1024 * 1024
```suggestion
var MaxFileSize = 20 * 1024 * 1024  // <сколько-это-в-мегабайтах>
```

2023-10-28 18:30 UTC, s-shpak commented on internal/server/grpc_client.go
> +		// c.clientCompressInterceptor,
deadcode ?

2023-10-28 18:30 UTC, s-shpak commented on internal/storage/sql/records.go
> +func (db *DB) List(ctx context.Context, userID string) ([]*models.Record, error) {
Здесь стоит добавить пагинацию (т.е. два параметра: length, offset)

2023-10-31 12:38 UTC, artemshalin commented on cmd/gagent/main.go
> +		if err := gagent.ListenAndServe(); err != nil {
Удалил агента.

2023-10-31 12:38 UTC, ArtemShalinFe commented on cmd/gagent/main.go
> +		const timeoutServerShutdown = time.Second * 10
Удалил агента.

2023-10-31 12:38 UTC, ArtemShalinFe commented on cmd/gagent/main.go
> +		const timeoutShutdown = time.Second * 30
Удалил агента.

2023-11-08 09:14 UTC, s-shpak requested changes
Вот проблемы, которые я нашел:

1. Запускаю pg, собираю клиента, запускаю его, получаю ошибку:

```
2023/11/08 10:05:22 an unexpected error occured, err: an error occure while init gk client, err: an error occured while setup conn to server, err: server is not available at , err: failed to build resolver: passthrough: received empty target in Build()
```

2. Запускаю сервер, получаю 

```
2023/11/08 10:10:28 an occured fatal error, err: an error occured when init db, err: failed to run DB migrations: failed to get a new migrate instance: URL cannot be empty
```

Пытаюсь выполнить `./gserver --help`, получаю ту же ошибку

Добавь, пожалуйста, инструкции, как запускать твой сервис

2023-11-08 09:14 UTC, s-shpak commented on deployments/docker-compose.yml
> +  # gclient:
deadcode ?

2023-11-08 09:14 UTC, s-shpak commented on cmd/gserver/gserver
Все еще в репозитории

2023-11-08 09:14 UTC, s-shpak commented on cmd/gclient/gclient
Все еще в репозитории

2023-11-08 09:14 UTC, s-shpak commented on deployments/docker-compose.yml
этот файл лучше положить в корень репозитория

2023-11-09 20:33 UTC, s-shpak approved these changes
LGTM!

2023-11-10 06:15 UTC, merged